#!/usr/bin/env bash
# configures an Ubuntu server.
# Requirements:
#	localhost resolves to 127.0.0.1
#	facebook.com resolves to 8.8.8.8
sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts
sudo sed -i '2i8.8.8.8	facebook.com' /etc/hosts
