#!/usr/bin/env bash
# configures an Ubuntu server.
# Requirements:
#	localhost resolves to 127.0.0.1
#	facebook.com resolves to 8.8.8.8
echo ;
echo "=============================================================="
echo "file /etc/hosts"
echo "=============================================================="
cat /etc/hosts
echo ;
sudo cp /etc/hosts /etc/hosts.old
sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts.old
sudo sed -i '2i8.8.8.8	facebook.com' /etc/hosts.old
echo ;
echo "=============================================================="
echo "file /etc/hosts.old"
echo "=============================================================="
cat /etc/hosts.old
echo ;
sudo cp /etc/hosts.old /etc/hosts.new
echo ;
echo "=============================================================="
echo "ping localhost"
echo "=============================================================="
echo ;
ping $1 -c 2
echo ;
echo "=============================================================="
echo "ping localhost"
echo "=============================================================="
echo ;
ping $2 -c 2
sudo mv /etc/hosts /etc/hosts.old
sudo mv /etc/hosts.new /etc/hosts
echo ;
echo "=============================================================="
echo "ping localhost"
echo "=============================================================="
echo ;
ping $1 -c 2
echo ;
echo "=============================================================="
echo "ping facebook.com"
echo "=============================================================="
ping $2 -c 2
sudo mv /etc/hosts.old /etc/hosts

